blank_issues_enabled: false
contact_links:
  - name: ğŸ“š DocumentaÃ§Ã£o
    url: https://cacic-fct.github.io/fct-app-docs
    about: Encontre guias e explicaÃ§Ãµes para perguntas frequentes.
  - name: ğŸ¤“ Encontrou um problema na documentaÃ§Ã£o?
    url: https://github.com/cacic-fct/fct-app-docs/issues/new
    about: Abra a issue no repositÃ³rio da documentaÃ§Ã£o.
  - name: ğŸ’¬ DiscussÃµes
    url: https://github.com/Tyrrrz/DiscordChatExporter/discussions/new
    about: Pergunte e interaja com outros usuÃ¡rios.